# Отчет по методам PyTorch

In [1]:
import numpy as np
import torch

## torch.cat()

Конкатенирует тензоры по заданной существующей оси. Тензоры должны иметь одинаковый размер по всем осям кроме той, по которой происходит конкатенация.

In [2]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[11, 12], [13, 14]])

In [3]:
a

tensor([[1, 2],
        [3, 4]])

In [4]:
b

tensor([[11, 12],
        [13, 14]])

In [5]:
torch.cat((a, b), 0)

tensor([[ 1,  2],
        [ 3,  4],
        [11, 12],
        [13, 14]])

In [6]:
torch.cat((a, b), 1)

tensor([[ 1,  2, 11, 12],
        [ 3,  4, 13, 14]])

## torch.chunk()

Разделяет тензор на равные (насколько это возможно) части.

Первый параметр – количество частей, второй параметр – ось, по которой происходит разделение.

Если размер тензора по данной оси нацело делится на количество частей, то все части будут равными. Если не делится, то все части, кроме последней, будут равными.

Если размер тензора по данной оси меньше, чем количество частей, то количество возвращенных частей будет равно размеру по оси, и все части будут иметь размер 1 по этой оси.

In [7]:
a = torch.rand(9, 9)
a

tensor([[0.0412, 0.5442, 0.5404, 0.8547, 0.4174, 0.6979, 0.5480, 0.4978, 0.6803],
        [0.5104, 0.2104, 0.5031, 0.7911, 0.9732, 0.5757, 0.5795, 0.6305, 0.9546],
        [0.7374, 0.9506, 0.9923, 0.1330, 0.8716, 0.9568, 0.2554, 0.1503, 0.9699],
        [0.8717, 0.6030, 0.1519, 0.0959, 0.8969, 0.4047, 0.9353, 0.3575, 0.2845],
        [0.9387, 0.3517, 0.2215, 0.5579, 0.5986, 0.5637, 0.0495, 0.2603, 0.3998],
        [0.4695, 0.9239, 0.8589, 0.1641, 0.4092, 0.0736, 0.1962, 0.2522, 0.2671],
        [0.4022, 0.1936, 0.4249, 0.0995, 0.8418, 0.5908, 0.4477, 0.2970, 0.0241],
        [0.5521, 0.7382, 0.9416, 0.9840, 0.8128, 0.2030, 0.3594, 0.4398, 0.0529],
        [0.7348, 0.7219, 0.3235, 0.1999, 0.5703, 0.5633, 0.8212, 0.2354, 0.6405]])

In [8]:
a.chunk(3, 0)

(tensor([[0.0412, 0.5442, 0.5404, 0.8547, 0.4174, 0.6979, 0.5480, 0.4978, 0.6803],
         [0.5104, 0.2104, 0.5031, 0.7911, 0.9732, 0.5757, 0.5795, 0.6305, 0.9546],
         [0.7374, 0.9506, 0.9923, 0.1330, 0.8716, 0.9568, 0.2554, 0.1503, 0.9699]]),
 tensor([[0.8717, 0.6030, 0.1519, 0.0959, 0.8969, 0.4047, 0.9353, 0.3575, 0.2845],
         [0.9387, 0.3517, 0.2215, 0.5579, 0.5986, 0.5637, 0.0495, 0.2603, 0.3998],
         [0.4695, 0.9239, 0.8589, 0.1641, 0.4092, 0.0736, 0.1962, 0.2522, 0.2671]]),
 tensor([[0.4022, 0.1936, 0.4249, 0.0995, 0.8418, 0.5908, 0.4477, 0.2970, 0.0241],
         [0.5521, 0.7382, 0.9416, 0.9840, 0.8128, 0.2030, 0.3594, 0.4398, 0.0529],
         [0.7348, 0.7219, 0.3235, 0.1999, 0.5703, 0.5633, 0.8212, 0.2354, 0.6405]]))

In [9]:
a.chunk(3, 1)

(tensor([[0.0412, 0.5442, 0.5404],
         [0.5104, 0.2104, 0.5031],
         [0.7374, 0.9506, 0.9923],
         [0.8717, 0.6030, 0.1519],
         [0.9387, 0.3517, 0.2215],
         [0.4695, 0.9239, 0.8589],
         [0.4022, 0.1936, 0.4249],
         [0.5521, 0.7382, 0.9416],
         [0.7348, 0.7219, 0.3235]]), tensor([[0.8547, 0.4174, 0.6979],
         [0.7911, 0.9732, 0.5757],
         [0.1330, 0.8716, 0.9568],
         [0.0959, 0.8969, 0.4047],
         [0.5579, 0.5986, 0.5637],
         [0.1641, 0.4092, 0.0736],
         [0.0995, 0.8418, 0.5908],
         [0.9840, 0.8128, 0.2030],
         [0.1999, 0.5703, 0.5633]]), tensor([[0.5480, 0.4978, 0.6803],
         [0.5795, 0.6305, 0.9546],
         [0.2554, 0.1503, 0.9699],
         [0.9353, 0.3575, 0.2845],
         [0.0495, 0.2603, 0.3998],
         [0.1962, 0.2522, 0.2671],
         [0.4477, 0.2970, 0.0241],
         [0.3594, 0.4398, 0.0529],
         [0.8212, 0.2354, 0.6405]]))

In [10]:
a.chunk(5, 0)

(tensor([[0.0412, 0.5442, 0.5404, 0.8547, 0.4174, 0.6979, 0.5480, 0.4978, 0.6803],
         [0.5104, 0.2104, 0.5031, 0.7911, 0.9732, 0.5757, 0.5795, 0.6305, 0.9546]]),
 tensor([[0.7374, 0.9506, 0.9923, 0.1330, 0.8716, 0.9568, 0.2554, 0.1503, 0.9699],
         [0.8717, 0.6030, 0.1519, 0.0959, 0.8969, 0.4047, 0.9353, 0.3575, 0.2845]]),
 tensor([[0.9387, 0.3517, 0.2215, 0.5579, 0.5986, 0.5637, 0.0495, 0.2603, 0.3998],
         [0.4695, 0.9239, 0.8589, 0.1641, 0.4092, 0.0736, 0.1962, 0.2522, 0.2671]]),
 tensor([[0.4022, 0.1936, 0.4249, 0.0995, 0.8418, 0.5908, 0.4477, 0.2970, 0.0241],
         [0.5521, 0.7382, 0.9416, 0.9840, 0.8128, 0.2030, 0.3594, 0.4398, 0.0529]]),
 tensor([[0.7348, 0.7219, 0.3235, 0.1999, 0.5703, 0.5633, 0.8212, 0.2354, 0.6405]]))

In [11]:
a.chunk(100, 0)

(tensor([[0.0412, 0.5442, 0.5404, 0.8547, 0.4174, 0.6979, 0.5480, 0.4978, 0.6803]]),
 tensor([[0.5104, 0.2104, 0.5031, 0.7911, 0.9732, 0.5757, 0.5795, 0.6305, 0.9546]]),
 tensor([[0.7374, 0.9506, 0.9923, 0.1330, 0.8716, 0.9568, 0.2554, 0.1503, 0.9699]]),
 tensor([[0.8717, 0.6030, 0.1519, 0.0959, 0.8969, 0.4047, 0.9353, 0.3575, 0.2845]]),
 tensor([[0.9387, 0.3517, 0.2215, 0.5579, 0.5986, 0.5637, 0.0495, 0.2603, 0.3998]]),
 tensor([[0.4695, 0.9239, 0.8589, 0.1641, 0.4092, 0.0736, 0.1962, 0.2522, 0.2671]]),
 tensor([[0.4022, 0.1936, 0.4249, 0.0995, 0.8418, 0.5908, 0.4477, 0.2970, 0.0241]]),
 tensor([[0.5521, 0.7382, 0.9416, 0.9840, 0.8128, 0.2030, 0.3594, 0.4398, 0.0529]]),
 tensor([[0.7348, 0.7219, 0.3235, 0.1999, 0.5703, 0.5633, 0.8212, 0.2354, 0.6405]]))

## torch.nonzero()

Возвращает индексы всех ненулевых элементов тензора.

In [12]:
a = torch.tensor([[1, 0, 2], [0, 3, 0], [4, 5, 0]])
a

tensor([[1, 0, 2],
        [0, 3, 0],
        [4, 5, 0]])

In [13]:
a.nonzero()

tensor([[0, 0],
        [0, 2],
        [1, 1],
        [2, 0],
        [2, 1]])

## torch.squeeze()

Удаляет все оси длины 1.

In [14]:
a = torch.tensor([[[[1], [0], [2]], [[0], [3], [0]], [[4], [5], [0]]]])
a

tensor([[[[1],
          [0],
          [2]],

         [[0],
          [3],
          [0]],

         [[4],
          [5],
          [0]]]])

In [15]:
a.shape

torch.Size([1, 3, 3, 1])

In [16]:
result = a.squeeze()
result

tensor([[1, 0, 2],
        [0, 3, 0],
        [4, 5, 0]])

In [17]:
result.shape

torch.Size([3, 3])

## torch.stack()

Конкатенирует тензоры по заданной новой оси.

Тензоры должны иметь одинаковый размер.

In [18]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = torch.tensor([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

In [19]:
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
b

tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [21]:
result = torch.stack((a, b), 0)
result

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [22]:
result.shape

torch.Size([2, 3, 3])

In [23]:
result = torch.stack((a, b), 1)
result

tensor([[[ 1,  2,  3],
         [11, 12, 13]],

        [[ 4,  5,  6],
         [14, 15, 16]],

        [[ 7,  8,  9],
         [17, 18, 19]]])

In [24]:
result.shape

torch.Size([3, 2, 3])

In [25]:
result = torch.stack((a, b), 2)
result

tensor([[[ 1, 11],
         [ 2, 12],
         [ 3, 13]],

        [[ 4, 14],
         [ 5, 15],
         [ 6, 16]],

        [[ 7, 17],
         [ 8, 18],
         [ 9, 19]]])

In [26]:
result.shape

torch.Size([3, 3, 2])

## torch.t()

Частный случай метода torch.transpose().

Транспонирует тензор.

У 2-мерных тензоров меняет местами оси 0 и 1, что эквивалентно transpose(0, 1)

Тензоры с меньшим количеством измерений возвращает неизмененными. 

В случае тензоров с большим количеством измерений возвращает ошибку.

In [27]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
a.t()

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## torch.transpose()

Обобщенная версия метода torch.t().

Меняет местами 2 заданные оси.

In [29]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
a.transpose(0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [31]:
b = torch.tensor([[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]]])
b

tensor([[[1, 1],
         [2, 2],
         [3, 3]],

        [[4, 4],
         [5, 5],
         [6, 6]]])

In [32]:
b.shape

torch.Size([2, 3, 2])

In [33]:
result = b.transpose(1, 2)
result

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6]]])

In [34]:
result.shape

torch.Size([2, 2, 3])

## torch.unbind()

Удаляет заданную ось. Возвращает все срезы (slice) по удаляемой оси.

In [35]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
a.unbind(0)

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [37]:
a.unbind(1)

(tensor([1, 4]), tensor([2, 5]), tensor([3, 6]))

## torch.unsqueeze()

Обратная функция к torch.squeeze().

Добавляет новую ось размера 1 в заданном месте.

In [38]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
a.shape

torch.Size([2, 3])

In [40]:
result = a.unsqueeze(2)
result

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [41]:
result.shape

torch.Size([2, 3, 1])

In [42]:
result = a.unsqueeze(1)
result

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [43]:
result.shape

torch.Size([2, 1, 3])

In [44]:
result = a.unsqueeze(0)
result

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [45]:
result.shape

torch.Size([1, 2, 3])

## torch.where()

Проверяет условие для каждого элемента тензора.

Если условие возвращает True, на это место берется элемент из первого тензора.

Если условие возвращает False, на это место берется элемент из второго тензора.

In [46]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [47]:
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [48]:
y = torch.ones(2, 3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [49]:
torch.where(a % 2 == 0, x, y)

tensor([[1., 0., 1.],
        [0., 1., 0.]])